config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "piscines#index"

  # get 'piscines/show'
  get 'piscines/index_perso'
  # get 'piscines/create'
  # get 'piscines/new'
  # get 'users/show'
  # get 'users/index'
  # get 'users/create'
  # get 'users/new'
  devise_for :admins
  devise_for :users

  resources :piscines

resources :piscines do
  get :filter, on: :collection, as: :filter
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # def self.ransackable_attributes(auth_object = nil)
  # ["created_at", "email", "encrypted_password", "id", "lastname", "mail", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "type", "updated_at"]
  # end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # def self.ransackable_attributes(auth_object = nil)
  #   ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end

end

app/models/piscine.rb
class Piscine < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  def format_heure_minutes
      formatted_fields = []
      self.attributes.each do |attr_name, attr_value|
        if attr_value.present? && attr_value.respond_to?(:strftime)
          formatted_fields << attr_value.strftime("%H:%M")
        elsif attr_value.respond_to?(:strftime)
          formatted_fields << "-"
        end
      end
      formatted_fields
    end

    # def self.ransackable_attributes(auth_object = nil)
    #   ["adress", "cp", "created_at", "fridayend", "fridaystart", "id", "mail", "mondayend", "mondaystart", "name", "pays", "saturdayend", "saturdaystart", "sundayend", "sundaystart", "tel", "thursdayend", "thursdaystart", "tuesdayend", "tuesdaystart", "updated_at", "user_id", "ville", "wednesdayend", "wednesdaystart"]
    # end
    # def self.ransackable_associations(auth_object = nil)
    #   ["image_attachment", "image_blob", "user"]
    # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :piscines
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # def self.ransackable_attributes(auth_object = nil)
  # ["created_at", "email", "encrypted_password", "id", "lastname", "mail", "name", "remember_created_at", "reset_password_sent_at", "reset_password_token", "type", "updated_at"]
  # end
  # def self.ransackable_associations(auth_object = nil)
  #   ["piscines"]
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/piscines_controller.rb
class PiscinesController < ApplicationController
  include Pagy::Backend

  def show
    @piscine = Piscine.find(params[:id])
  end

  def index
    # @piscines = Piscine.all
    @pagy, @piscines = pagy(Piscine.all)
  end

  def index_perso
    @pagy, @piscines = pagy(Piscine.where(user: current_user))
  end

  def new
    @piscine = current_user.piscines.build
  end

  def create
    @piscine = current_user.piscines.build(piscine_params)
  
    if @piscine.save
      redirect_to @piscine, notice: 'Piscine créée avec succès.'
    else
      render :new
    end
  end

  def destroy
    # load existing object again from URL param
    piscine = Piscine.find(params[:id])
    # destroy object
    piscine.destroy
    # respond_to block
    respond_to do |format|
        format.html do
            # success message
            flash[:success] = 'Piscine removed successfully'
            # redirect to index
            redirect_to root_path
        end
    end
  end

def edit
  @piscine = Piscine.find(params[:id])
  respond_to do |format|
      format.html { render :edit, locals: { piscine: @piscine } }
  end
end

def filter
  @piscines = Piscine.filter(params[:query])

  respond_to do |format|
    format.turbo_stream do
      render turbo_stream: turbo_stream.replace(
        "piscines_frame",
        partial: "piscines/list", locals: { piscines: @piscines }
      )
    end
  end
end

# def update
#   # load existing object again from URL param
#   @piscine = Piscine.find(params[:id])
#   # respond_to block
#   respond_to do |format|
#       format.html do
#           if @piscine.update(params.require(:piscine).permit(:name, :adress, :cp, :ville, :pays, :mail, :tel, :user, :mondaystart, :mondayend, :tuesdaystart, :tuesdayend, :wednesdaystart, :wednesdayend, :thursdaystart, :thursdayend, :fridaystart, :fridayend, :saturdaystart, :saturdayend, :sundaystart, :sundayend))
#               # success message
#               flash[:success] = 'Piscine updated successfully'
#               # redirect to index
#               redirect_to root_path
#           else
#               # error message
#               flash.now[:error] = 'Error: Piscine could not be updated'
#               # render edit
#               render :edit, locals: { piscine: @piscine }
#           end
#       end
#   end
# end

def update
  @piscine = Piscine.find(params[:id])

  if @piscine.update(piscine_params)
    redirect_to @piscine
  else
    flash.now[:error] = 'Error: Piscine could not be updated'
    render 'edit'
  end
end


private
 
  def piscine_params
    params.require(:piscine).permit(:name, :adress, :cp, :ville, :pays, :mail, :tel, :mondaystart, :mondayend, :tuesdaystart, :tuesdayend, :wednesdaystart, :wednesdayend, :thursdaystart, :thursdayend, :fridaystart, :fridayend, :saturdaystart, :saturdayend, :sundaystart, :sundayend, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
  end

  def create
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
    include Pagy::Frontend
  end

app/helpers/piscines_helper.rb
module PiscinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PPT</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

  </head>

  <body class="all_page_background">
    <nav class="nav">
        <div class="container">
            <div class="logo">
                <%= link_to "Piscine pour tou te s", root_path %>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <% if user_signed_in? %>
                      <li><a href="/piscines/index_perso">Logged in as <%= current_user.email %></a> </li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <li><%= link_to "Ajouter une piscine", new_piscine_path %></li>
                    <% else %>
                      <li><%= link_to "Sign up", new_user_registration_path %> </li>
                      <li><%= link_to "Sign in", new_user_session_path %></li>
                    <% end %>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>
    <%= yield %>
  </body>
  <!-- Jquery needed -->
    <%# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> %>
    
    <%# <script src="js/scripts.js"></script> %>

<!-- Function used to shrink nav bar removing paddings and adding black background -->
    <%# <script>
        $(window).scroll(function() {
            if ($(document).scrollTop() > 50) {
                $('.nav').addClass('affix');
                console.log("OK");
            } else {
                $('.nav').removeClass('affix');
            }
        });
    </script> %>
</html>

app/views/piscines/_list.html.erb
<div class="piscine-card">
           <% horaires = piscine.format_heure_minutes %>
          <div class="piscine-photo-bloc">
            <div class="piscine-photo"> 
              <%# <%= image_tag('gettyimages-140872616-612x612.jpg')%>
              <%= image_tag url_for(piscine.image) if piscine.image.attached? %>
            </div>
          </div>
          <div class="piscine-details">
            <h2 class="piscine-titre"><%= piscine.name %></h2>
            <p class="piscine-adresse"><%= piscine.adress %> <%= piscine.cp %> <%= piscine.ville %></p>
            <h3 class="piscine-sous-titre">Horaires:</h3>
            <ul class="piscine-horaires">
              <li>Lundi: <%=horaires[0]%> - <%=horaires[1]%></li>
              <li>Mardi: <%=horaires[2]%> - <%=horaires[3]%></li>
              <li>Mercredi: <%=horaires[4]%> - <%=horaires[5]%></li>
              <li>Jeudi: <%=horaires[6]%> - <%=horaires[7]%></li>
              <li>Vendredi: <%=horaires[8]%> - <%=horaires[9]%></li>
              <li>Samedi: <%=horaires[10]%> - <%=horaires[11]%></li>
              <li>Dimanche: <%=horaires[12]%> - <%=horaires[13]%></li>
            </ul>
            <a href="piscines/<%=piscine.id%>" class="piscine-bouton">Detail</a>
          </div>
        </div>        
      

app/views/piscines/create.html.erb
<h1>Piscines#create</h1>
<p>Find me in app/views/piscines/create.html.erb</p>

app/views/piscines/edit.html.erb
<div class="top-space">
</div>

<div class="piscine-form">
  <h2>Modifier une piscine </h2>
<%= form_for @piscine do |f| %>
  <% if @piscine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piscine.errors.count, "erreur") %> a interdit l'enregistrement de cette piscine :</h2>

      <ul>
      <% @piscine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nom" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :adress, "Adresse" %>
    <%= f.text_field :adress %>
  </div>

  <div class="field">
    <%= f.label :cp, "Code Postal" %>
    <%= f.text_field :cp %>
  </div>

  <div class="field">
    <%= f.label :ville, "Ville" %>
    <%= f.text_field :ville %>
  </div>

  <div class="field">
    <%= f.label :pays, "Pays" %>
    <%= f.text_field :pays %>
  </div>

  <div class="field">
    <%= f.label :mail, "Email" %>
    <%= f.text_field :mail %>
  </div>

  <div class="field">
    <%= f.label :tel, "Téléphone" %>
    <%= f.text_field :tel %>
  </div>

  <div class="field">
    <%= f.file_field :image %>
  </div>
  <!-- Les horaires par jour -->
  
  <div class="field">
    <%= f.label :mondaystart, "Lundi début" %>
    <%= f.time_select :mondaystart %>
    <%= f.label :mondayend, "fin" %>
    <%= f.time_select :mondayend %>
  </div>

  <div class="field">
    <%= f.label :tuesdaystart, "Mardi début" %>
    <%= f.time_select :tuesdaystart %>
    <%= f.label :tuesdayend, "fin" %>
    <%= f.time_select :tuesdayend %>
  </div>

  <div class="field">
    <%= f.label :wednesdaystart, "Mercredi début" %>
    <%= f.time_select :wednesdaystart %>
    <%= f.label :wednesdayend, "fin" %>
    <%= f.time_select :wednesdayend %>
  </div>

  <div class="field">
    <%= f.label :thursdaystart, "Jeudi début" %>
    <%= f.time_select :thursdaystart %>
    <%= f.label :thursdayend, "fin" %>
    <%= f.time_select :thursdayend %>
  </div>

  <div class="field">
    <%= f.label :fridaystart, "Vendredi début" %>
    <%= f.time_select :fridaystart %>
    <%= f.label :fridayend, "fin" %>
    <%= f.time_select :fridayend %>
  </div>

  <div class="field">
    <%= f.label :saturdaystart, "Samedi début" %>
    <%= f.time_select :saturdaystart %>
    <%= f.label :saturdayend, "fin" %>
    <%= f.time_select :saturdayend %>
  </div>

  <div class="field">
    <%= f.label :sundaystart, "Dimanche début" %>
    <%= f.time_select :sundaystart %>
    <%= f.label :sundayend, "fin" %>
    <%= f.time_select :sundayend %>
  </div>

  <div class="actions">
    <%= f.submit "Enregistrer les modifications" %>
  </div>

<% end %>

</div>

app/views/piscines/index.html.erb
    <section class="home">
    </section>

    <section >
    <div style="height: 300px">
        <!-- just to make scrolling effect possible -->
			<h2 class="myH2">Bienvenu</h2>
			<p class="myP">inscrit toi et crée tes listes de piscines personnalisés, d'enregistrer leurs horaires et de tjr savoir si ta piscine preferée est ouverte. </p>
			<%# <p class="myP">I took inspiration from  ABDO STEIF (<a href="https://codepen.io/abdosteif/pen/bRoyMb?editors=1100">https://codepen.io/abdosteif/pen/bRoyMb?editors=1100</a>)
			and Dicson <a href="https://codepen.io/dicson/pen/waKPgQ">(https://codepen.io/dicson/pen/waKPgQ)</a></p> %>
			<p class="myP">Deja plus de <%=@piscines.count%> piscines ajoutées! Trouve la tienne!</p>
      <!-- Bouton pour ouvrir la modale -->
        <button id="openModalButton">Ouvrir le chat</button>

      <!-- Structure de base pour la modale -->
          <div id="chatModal" class="modal" style="display:none;">
            <div class="modal-content">
                <div class="modal-header">
                  <span id="closeModalButton" class="close">&times;</span>
                  <h2>Chat</h2>
                </div>
                <!-- Corps de la modale : historique des messages -->
                <div class="modal-body">
                  <div class="messages">
                    <!-- Les messages seront ajoutés ici dynamiquement -->
                  </div>
                </div>
                <!-- Pied de page de la modale : zone de saisie des messages -->
                <div class="modal-footer">
                  <input type="text" id="messageInput" placeholder="Écrire un message...">
                  <button id="sendMessage">Envoyer</button>
                </div>
            </div>
          </div>
			<%# <p class="myP">Albi</p> %>
    </section>

    <%= form_with(url: filter_piscines_path, method: "get", data: { turbo_frame: "piscines_frame" }, remote: true) do |form| %>
      <%= form.search_field :ville, id: "villeFilter", class: "filter-input", placeholder: "Filtrer par ville" %>
      <%= form.submit "Filtrer" %>
    <% end %>


    <section >
      <div class="grille-cartes">
        <turbo-frame id="piscines_frame">
        <% @piscines.each do |piscine| %>
      
        <%= render partial: "list", locals: { piscine: piscine } %>
        <%end%>
       </turbo-frame>
      </div>
       <%= pagy_bootstrap_nav(@pagy).html_safe %>
    </section>

    <%# <script>
  document.addEventListener('DOMContentLoaded', (event) => {
    const openModalButton = document.getElementById('openModalButton');
    const modal = document.getElementById('chatModal');
    const closeModalButton = document.getElementById('closeModalButton');
  
    openModalButton.addEventListener('click', () => {
      console.log("Bouton d'ouverture de la modale cliqué1");
      modal.style.display = 'block';
    });
  
    closeModalButton.addEventListener('click', () => {
      modal.style.display = 'none';
    });
  
    window.addEventListener('click', (event) => {
      if (event.target == modal) {
        modal.style.display = 'none';
      }
    });
  });
</script> %>

app/views/piscines/index_perso.html.erb
<div class="top-space">
</div>
	<p class="myP">Mes piscines </p>

    <section >
      <div class="grille-cartes">
        <% @piscines.each do |piscine| %>
        <% horaires = piscine.format_heure_minutes %>

        <div class="piscine-card">
          <div class="piscine-photo-bloc">
            <div class="piscine-photo"> 
              <%= image_tag url_for(piscine.image) if piscine.image.attached? %>
            </div>
          </div>
          <div class="piscine-details">
            <h2 class="piscine-titre"><%= piscine.name %></h2>
            <p class="piscine-adresse"><%= piscine.adress %> <%= piscine.cp %> <%= piscine.ville %></p>
            <h3 class="piscine-sous-titre">Horaires:</h3>
            <ul class="piscine-horaires">
              <li>Lundi: <%=horaires[0]%> - <%=horaires[1]%></li>
              <li>Mardi: <%=horaires[2]%> - <%=horaires[3]%></li>
              <li>Mercredi: <%=horaires[4]%> - <%=horaires[5]%></li>
              <li>Jeudi: <%=horaires[6]%> - <%=horaires[7]%></li>
              <li>Vendredi: <%=horaires[8]%> - <%=horaires[9]%></li>
              <li>Samedi: <%=horaires[10]%> - <%=horaires[11]%></li>
              <li>Dimanche: <%=horaires[12]%> - <%=horaires[13]%></li>
            </ul>
            <a href="./<%=piscine.id%>" class="piscine-bouton">Detail</a>
            <%= button_to "delete", {:controller => :piscines,
      :action => 'destroy', :id => piscine.id }, :method => :delete %>
            <%= button_to "update", {:controller => :piscines,
      :action => 'edit', :id => piscine.id }, :method => :get %>
          </div>
        </div>        
        <%end%>
       
      </div>
       <%= pagy_bootstrap_nav(@pagy).html_safe %>
    </section>

app/views/piscines/new.html.erb
<div class="top-space">
</div>

<div class="piscine-form">
  <h2>Ajouter une piscine </h2>
<%= form_with(model: @piscine, url: piscines_path, local: true) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name, class: "piscine-field" %>
  </div>
  
  <div>
    <%= form.label :adress %>
    <%= form.text_field :adress, class: "piscine-field" %>
  </div>
  <div>
    <%= form.label :cp %>
    <%= form.text_field :cp, class: "piscine-field" %>
  </div>
  <div>
    <%= form.label :ville %>
    <%= form.text_field :ville, class: "piscine-field" %>
  </div>
  <div>
    <%= form.label :pays %>
    <%= form.text_field :pays, class: "piscine-field" %>
  </div>
  <div>
    <%= form.label :mail %>
    <%= form.text_field :mail, class: "piscine-field" %>
  </div>
  <div>
    <%= form.label :tel %>
    <%= form.text_field :tel, class: "piscine-field" %>
  </div>
  <div>
    <%= form.file_field :image %>
  </div>

  <div>
    <p>Lundi:
    <%= form.label "Ouverture" %>
    <%= form.time_field :mondaystart, class: "piscine-time-field" %>
  
    <%= form.label "fermeture" %>
    <%= form.time_field :mondayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Mardi: 
    <%= form.label "Ouverture" %>
    <%= form.time_field :tuesdaystart, class: "piscine-time-field" %>
  
    <%= form.label "Fermeture"%>
    <%= form.time_field :tuesdayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Mercredi:
    <%= form.label "Ouverture" %>
    <%= form.time_field :wednesdaystart, class: "piscine-time-field" %>
 
    <%= form.label "Fermeture" %>
    <%= form.time_field :wednesdayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Jeudi:
    <%= form.label "Ouverture" %>
    <%= form.time_field :thursdaystart, class: "piscine-time-field" %>
  
    <%= form.label "Fermeture" %>
    <%= form.time_field :thursdayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Vendredi:
    <%= form.label "Ouverture" %>
    <%= form.time_field :fridaystart, class: "piscine-time-field" %>
  
    <%= form.label "Fermeture" %>
    <%= form.time_field :fridayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Samedi:
    <%= form.label "Ouverture" %>
    <%= form.time_field :saturdaystart, class: "piscine-time-field" %>
  
    <%= form.label "Fermeture" %>
    <%= form.time_field :saturdayend, class: "piscine-time-field" %>
    </p>
  </div>
  <div>
    <p>Dimanche:
    <%= form.label "Ouverture" %>
    <%= form.time_field :sundaystart, class: "piscine-time-field" %>
 
    <%= form.label "fermeture" %>
    <%= form.time_field :sundayend, class: "piscine-time-field" %>
    </p>
  </div>

  <%= form.submit "Créer", class: "log-btn" %>
<% end %>
</div>

app/views/piscines/show.html.erb
<div class="top-space">
</div>

<div class="piscine-show-card">
    <% horaires = @piscine.format_heure_minutes %>
        <div class="piscine-photo-bloc">
            <div class="piscine-photo"> 
                <%# <%= image_tag('gettyimages-140872616-612x612.jpg')%>
                <%= image_tag url_for(@piscine.image) if @piscine.image.attached? %>
            </div>
        </div>
        <div class="piscine-details">
            <h2 class="piscine-titre"><%= @piscine.name %></h2>
            <p class="piscine-adresse"><%= @piscine.adress %> <%= @piscine.cp %> <%= @piscine.ville %></p>
            <h3 class="piscine-sous-titre">Horaires:</h3>
            <ul class="piscine-horaires">
                <li>Lundi: <%=horaires[0]%> - <%=horaires[1]%></li>
                <li>Mardi: <%=horaires[2]%> - <%=horaires[3]%></li>
                <li>Mercredi: <%=horaires[4]%> - <%=horaires[5]%></li>
                <li>Jeudi: <%=horaires[6]%> - <%=horaires[7]%></li>
                <li>Vendredi: <%=horaires[8]%> - <%=horaires[9]%></li>
                <li>Samedi: <%=horaires[10]%> - <%=horaires[11]%></li>
                <li>Dimanche: <%=horaires[12]%> - <%=horaires[13]%></li>
            </ul>
        
             <%if @piscine.user.id == current_user.id%> 
                <%= button_to "delete", {:controller => :piscines, :action => 'destroy', :id => @piscine.id }, :method => :delete %>
                <%= button_to "update", {:controller => :piscines, :action => 'edit', :id => @piscine.id }, :method => :get %>
             <%else%>
            <%end%> 
        </div>
</div>        

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="top-space">
</div>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>